name: Build and Publish
on:
  push:
    branches: [ main ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --local user.name "Build and Publish Bot"
      - run: git config --local user.email "Jin-Hyeok.Cha@outlook.kr"
      - run: npm i
      - run: rm -rf docs
      - run: npx parcel build --public-url . --dist-dir docs index.html
      - run: git add docs
      - run: git commit -m "v$(cat package.json | jq -r .version), $(date)"
      - run: git push